name: Signed Commit with GitHub Token

on:
  pull_request:
  push:
    branches:
      - main  # Change this if needed

permissions:
  contents: write  # Required for committing changes

jobs:
  commit_changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Make changes
        run: |
          # Add your script or command here to make changes
          echo "New changes" >> changes2.txt
          
      - uses: planetscale/ghcommit-action@v0.2.4
        with:
          commit_message: "🤖 fmt"
          repo: ${{ github.repository }}
          branch: ${{ github.head_ref || github.ref_name }}
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
