name: Signed Commit with GitHub Token

on:
  pull_request:
  push:
    branches:
      - main  # Change this if needed

permissions:
  contents: write  # Required for committing changes

jobs:
  commit_changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make changes
        run: |
          # Add your script or command here to make changes
          echo "New changes" >> changes.txt
          
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Apply changes signed
